name: Run Script Once

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script-once:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Adjust Python version as needed
    - name: Generate requirements.txt
      run: |
        pip install pipreqs
        pipreqs . --force
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install pushbullet.py==0.9.1

    - name: Run Script
      env:
        WAIT_TIME_AFTER_SCRAPING: ${{ vars.WAIT_TIME_AFTER_SCRAPING }}
        PB_KEY: ${{ secrets.PB_KEY }}
        run: echo "My ${{ secrets.PB_KEY }} value is ${{ vars.WAIT_TIME_AFTER_SCRAPING }}"
      run: python main.py  # Run your script
